spring:
  application:
    name: items

server:
  port: ${item.port:8071}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01:8761/eureka
  instance:
    hostname: eureka02
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}